const express = require('express');
const cookieParser = require('cookie-parser');
const { connectDB } = require('../../shared/utils/db');
const { MONGO_URI } = require('../../shared/config');
const errorHandler = require('../../shared/middleware/errorHandler');
const app = express();
const PORT = process.env.OPS_SERVICE_PORT || 4003;
app.use(express.json());
app.use(cookieParser());
app.get('/health', (req, res) => res.json({ ok: true, service: 'operations' }));
app.use('/api/attendance', require('./routes/attendanceRoutes'));
app.use('/api/leaves', require('./routes/leaveRoutes'));
app.use('/api/shifts', require('./routes/shiftRoutes'));
app.use(errorHandler);
connectDB(MONGO_URI).then(() => { app.listen(PORT, () => console.log(`Operations Service listening on port ${PORT}`)); });
