const express = require('express');
const a = require('../controllers/attendanceController');
const { verifyToken, requireRoles } = require('../../../shared/middleware/authMiddleware');
const { auditMiddleware } = require('../../../shared/middleware/auditLogger');
const router = express.Router();
router.use(verifyToken);
router.use(auditMiddleware('attendance'));
router.get('/', a.list);
router.post('/', a.mark);
router.post('/bulk', requireRoles('admin', 'supervisor'), a.bulkMark);
router.delete('/:id', requireRoles('admin'), a.remove);
module.exports = router;
